name: calendar_time
description: Implementation of MomentJS's calendar time, plus a bunch of other helper methods.
version: 2.3.0
homepage: https://github.com/rknell/calendar_time

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.19.0

dev_dependencies:
  test:
  matcher: ^0.12.16
